### ISSUE TITLE
Failure when Delphix's ZFS packages don't match Ubuntu's "latest" kernel package

### ISSUE THREAD

**Issue by prakashsurya** [delphix/appliance-build#103]
When Ubuntu rolls a new kernel package version, appliance-build will fail with a message similar to the following:
```                                                                                
15:13:17 + echo 'Error: multiple kernel versions detected:'                        
15:13:17 Error: multiple kernel versions detected:                                 
15:13:17 + ls binary/lib/modules                                                   
15:13:17 4.15.0-33-generic                                                         
15:13:17 4.15.0-34-generic                                                         
15:13:17 + exit 1                                                                  
15:13:17 E: config/hooks/81-upgrade-repository.binary failed (exit non-zero). You should check for errors.
```                                                                                
                                                                                   
This will happen up until the point that our Delphix ZFS packages are updated to match this new kernel version.
                                                                                   
When running appliance-build, we supply a pointer (AWS S3 URI) to the "lastest" ZFS package that we've built, and install this specific package. Additionally, we always install the "lastest" kernel package provided by Ubuntu.
                                                                                   
This problem arises when the kernel version that our ZFS Delphix packages depends on does not match the "latest" kernel package version supplied by Ubuntu. What happens is we install Ubuntu's "latest" kernel version, via [this file](https://github.com/delphix/appliance-build/blob/master/live-build/base/config/package-lists/minimal.list.chroot), and then we _also_ install the kernel package that the Delphix ZFS packages depend on (due to `apt` automatically pulling in the package's dependencies).
                                                                                
As a result, we wind up with two different kernel packages installed, each package being a different kernel version. We specifically don't  want to wind up with an image with two kernel packages installed, so we fail the build when we detect this situation (with the error message shown above).
                                                                                
The "workaround" to fix this, is to:                                            
                                                                                
1. manually trigger a rebuild of our Delphix ZFS packages when this occurs, such that the ZFS package build will detect the new Ubuntu kernel package, and build new packages that depend on this new kernel version.
                                                                                
2. manually trigger a rebuild of appliance-build, after the new Delphix ZFS packages have been successfully built. This way, the new build will pick up the new ZFS packages, which will depend on the same kernel version provided by Ubuntu.

**Comment by grwilson** [comment]
Hit by this build: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/205/

**Comment by pzakha** [comment]
This will probably get somewhat better once we switch to the Ubuntu mirror, but the race condition won't go away fully since there is no guarantees the appliance and packages are built using the same mirror. I don't see any easy way to fix this, that said the time frame for the race condition should be relatively short.

**Comment by sdimitro** [comment]
We've hit this twice today:
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/2138/consoleFull
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/2139/consoleFull
```
05:09:14 + echo 'Error: multiple kernel versions detected:'
05:09:14 Error: multiple kernel versions detected:
05:09:14 + ls binary/lib/modules
05:09:14 4.18.0-1011-azure
05:09:14 4.18.0-1013-azure
```

**Comment by pzakha** [comment]
## Workaround
Note: the current way to workaround this issue is to launch a new linux-pkg/kernel build here: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/post-push/

**Comment by pzakha** [comment]
This type of issues should not happen anymore with the linux-pkg rework and the build of our in-house kernel.
