### ISSUE TITLE
Appliance build fails with "Failed to update apt cache"

### ISSUE THREAD

**Issue by shartse** [delphix/appliance-build#118]
I've seen this in two different builds, the first running on a schedule and the second when I was testing a build change at around the same time:
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/4/
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/12/flowGraphTable/

The error:
```
18:50:25 fatal: [binary]: FAILED! => {
18:50:25     "changed": false, 
18:50:25     "invocation": {
18:50:25         "module_args": {
18:50:25             "allow_unauthenticated": false, 
18:50:25             "autoclean": false, 
18:50:25             "autoremove": false, 
18:50:25             "cache_valid_time": 0, 
18:50:25             "deb": null, 
18:50:25             "default_release": null, 
18:50:25             "dpkg_options": "force-confdef,force-confold", 
18:50:25             "force": false, 
18:50:25             "force_apt_get": false, 
18:50:25             "install_recommends": null, 
18:50:25             "only_upgrade": false, 
18:50:25             "package": null, 
18:50:25             "purge": false, 
18:50:25             "state": "present", 
18:50:25             "update_cache": true, 
18:50:25             "upgrade": null
18:50:25         }
18:50:25     }, 
18:50:25     "msg": "Failed to update apt cache: "
18:50:25 }
```
This seems like a periodic availability issue which should be improved once we're using local apt repos. However, there hasn't yet been a successful build since the failure, so I'm not yet sure if this is an intermittent issue. I'm re-running the build to see if it's persistent.

**Comment by pzakha** [comment]
This might be related to the artifactory downtime. Looking at the first link, we can see those lines a bit before the failure:
```
20:26:21 Err:10 http://artifactory.****.com/artifactory/appliance-packages stable InRelease
20:26:21   Connection failed [IP: 172.16.105.84 80]
20:26:21 Reading package lists...
20:26:21 W: Failed to fetch http://artifactory.****.com/artifactory/appliance-packages/dists/stable/InRelease  Connection failed [IP: 172.16.105.84 80]
20:26:21 W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by prakashsurya** [comment]
that's right.. I forgot we use Artifactory as an APT repository, since 17a083b.. in that case, we can probably close this.
