### ISSUE TITLE
hitting SHA256SUMS error for the virtualization package

### ISSUE THREAD

**Issue by shartse** [delphix/appliance-build#150]
We seem to have hit a failure caused by a error when checksumming the app gate package. 

```
14:13:17 + aws s3 sync --only-show-errors s3://snapshot-de-images/builds/jenkins-ops/dlpx-app-gate/master/build-package/post-push/619 .
14:13:40 + sha256sum -c --strict SHA256SUMS
14:13:40 SHA256SUMS: FAILED
14:13:40 THIRD-PARTY-NOTICES.txt: OK
.
.
.
14:13:52 metadata.json: OK
14:13:52 sha256sum: WARNING: 1 computed checksum did NOT match
14:13:52 toolkit-devkit.tar: OK
14:13:52 make: *** [ancillary-repository] Error 1
14:13:52 Makefile:54: recipe for target 'ancillary-repository' failed
```
build: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/185/

**Comment by shartse** [comment]
Concluson: The file `SHA256SUMS` has a list of computed checksums for every file (including itself) in the package download. All of the checksums for these files are correct, except for that of `SHA256SUMS` itself. It doesn't make sense to have a checksum of the checksums file (due to recursion..).

**Comment by prakashsurya** [comment]
@shartse should we close this? now that we know the issue was in the virtualization build artifacts, and that's since been fixed.

**Comment by shartse** [comment]
This was addressed on the package build side.
