### ISSUE TITLE
Fix error handling in "build-ancillary-repository.sh"

### ISSUE THREAD

**Issue by prakashsurya** [delphix/appliance-build#155]
Currently, in the `build-ancillary-repository.sh` script, we (attempt to) rely on `set -o errexit` as a way to abort early whenever a command fails. Unfortunately, this setting is lost when executing a given function inside of a subshell. For example, we do things like this:
```
AWS_S3_URI_VIRTUALIZATION=$(resolve_s3_uri \                                    
        "$AWS_S3_URI_VIRTUALIZATION" \                                          
        "$AWS_S3_PREFIX_VIRTUALIZATION" \                                       
        "dlpx-app-gate/master/build-package/post-push/latest") 
```
Thus, any commands that fail from within the `resolve_s3_uri` function are not subject to the `set -o errexit` semantics because `set -o errexit` is only set at the top of the script (outside of any functions).

We should do one of the following to fix the problem:

1. Stop relying on `set -o errexit` for error handling altogether, or...
2. Annotate each function in that script with a unique `set -o errexit` call

**Comment by jgallag88** [comment]
My understanding was that the `set -o errexit` semantics are preserved in a subshell. For example
```
$ bash -c 'false; true'; echo $?
0
$ bash -ec 'false; true'; echo $?
1
$ bash -ec 'foo=$(false); true'; echo $?
1
```
Do we have an example where this isn't the case?

**Comment by prakashsurya** [comment]
@jgallag88 here's an example:
```
$ bash -ec 'false; true; echo hi;'
$ bash -ec '$(false; true); echo hi;'
hi
```
if the last command run in the subshell, it doesn't return an error, it won't fail the script; unlike if we run those same commands outside of the subshell.

**Comment by pzakha** [comment]
@prakashsurya I think this bug was fixed. I've tried passing an invalid S3 URI:

**Comment by pzakha** [comment]
Closing this as we haven't seen this for over a year.
