### ISSUE TITLE
Allow downgrading packages during appliance upgrade

### ISSUE THREAD

**Issue by pzakha** [delphix/appliance-build#159]
We are performing an upgrade by installing the new `delphix-entire` package. This currently succeeds because all the dependent package versions are monotonically increasing. However, this might not always be the case, and the new `delphix-entire` would fail to be installed if one of the dependencies has to be downgraded. We need to set apt preferences in such a way that allows downgrades. See https://github.com/delphix/appliance-build/pull/151/files for an example on how to do this.

**Comment by prakashsurya** [comment]
Copying the relevant code from that link to ensure we still have it, in case that link changes...
```
#
# This sets the prefereces for the ancillary repository added in sources file
# localhost.list. Any package coming from that repository will have the highest
# priority. Since the priority value is over 1000, downgrades will be allowed
# to satisfy package dependencies.
#

Package: *
Pin: origin "localhost"
Pin-Priority: 1001
```

**Comment by pzakha** [comment]
Been fixed a while ago.
