### ISSUE TITLE
Some packages fail to upgrade because they call update-grub

### ISSUE THREAD

**Issue by pzakha** [delphix/appliance-build#185]
Some packages fail to upgrade because they run `update-grub`, which doesn't currently work in our `systemd-nspawn` container since we do not mount `/dev`. In this case the package was `kdump-tools` and it was calling `update-grub` as part of its postinst hook, but there is a few other packages that call that as part of their hooks (you can try at `grep -r update-grub /var/lib/dpkg/`).

`update-grub` is a think wrapper script, which calls `grub-mkconfig -o /boot/grub/grub.cfg` and updates `/boot/grub/grub.conf`. It fails because it calls `grub-probe`, which tries to figure out which disk to install grub on and that fails when `/dev` is not mounted.

We had a similar issue previously when we were testing upgrade in chroot rather than in systemd-nspawn. In that case the workaround was to rename/remove `/etc/kernel/postinst.d/zz-update-grub`. This doesn't apply in this case however, since hooks in `/etc/kernel/postinst.d` only apply to kernel upgrades and not other upgrades. Moreover `zz-update-grub` actually does the right thing by calling:
```
if type systemd-detect-virt >/dev/null 2>&1 &&
   systemd-detect-virt --quiet --container; then
	exit 0
fi
```
This makes it correctly return success when ran in a `systemd-nspawn` container (a chroot isn't a container however, which is why we needed that workaround earlier).

A solution to this problem could be to modify `update-grub` to return right away when ran from the container, or to temporarily remove `/boot/grub/grub.conf` in the container since I the callers of `update-grub` skip the call if that file is not found.

**Comment by prakashsurya** [comment]
fixed via #187
