### ISSUE TITLE
Delete apt cache before creating images 

### ISSUE THREAD

**Issue by pzakha** [delphix/appliance-build#192]
We are currently wasting 3.2GB of each one of our image with cached debs in `/var/cache/apt`. We should not include this directory in our images.

**Comment by prakashsurya** [comment]
Doing this cleanup was also mentioned in #97.

**Comment by prakashsurya** [comment]
Fixed: https://github.com/delphix/appliance-build/commit/0240570800138b21bdda5b7516be1a8f35d6ed89
