### ISSUE TITLE
Task '...' not found in root project 'appliance-build'.

### ISSUE THREAD

**Issue by pnumboori** [delphix/appliance-build#236]
Task '...' not found in root project 'appliance-build'.

 ./scripts/docker-run.sh gradle ...
+ tty -s
+ DOCKER_RUN='docker run -ti'
+ docker run -ti --rm --privileged --network host --ipc none --volume /dev:/dev --env AWS_S3_PREFIX_VIRTUALIZATION --env AWS_S3_PREFIX_LINUX_PKG --env AWS_S3_PREFIX_MASKING --env AWS_S3_PREFIX_ZFS --env AWS_S3_URI_VIRTUALIZATION --env AWS_S3_URI_LINUX_PKG --env AWS_S3_URI_MASKING --env AWS_S3_URI_ZFS --env AWS_S3_URI_LIVEBUILD_ARTIFACTS --env APPLIANCE_PASSWORD --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env DELPHIX_SIGNATURE_URL --env DELPHIX_SIGNATURE_TOKEN --env DELPHIX_PLATFORMS --env DELPHIX_APPLIANCE_VERSION --volume /media/praveen/new/delphix/appliance-build:/opt/appliance-build --workdir /opt/appliance-build appliance-build gradle ...
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* What went wrong:
Task '...' not found in root project 'appliance-build'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by prakashsurya** [comment]
Hi @pnumboori! The `...` in the documentation is not meant to be used directly, but rather to denote the use of one of the gradle tasks; e.g. `buildInternalMinimalKvm` (as seen in the [quickstart section](https://github.com/delphix/appliance-build#quickstart-for-the-impatient)).

**Comment by pnumboori** [comment]
Thank you for replying.tried that:

./scripts/docker-run.sh gradle buildInternalMinimalKvm
+ tty -s
+ DOCKER_RUN='docker run -ti'
+ docker run -ti --rm --privileged --network host --ipc none --volume /dev:/dev --env AWS_S3_PREFIX_VIRTUALIZATION --env AWS_S3_PREFIX_LINUX_PKG --env AWS_S3_PREFIX_MASKING --env AWS_S3_PREFIX_ZFS --env AWS_S3_URI_VIRTUALIZATION --env AWS_S3_URI_LINUX_PKG --env AWS_S3_URI_MASKING --env AWS_S3_URI_ZFS --env AWS_S3_URI_LIVEBUILD_ARTIFACTS --env APPLIANCE_PASSWORD --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env DELPHIX_SIGNATURE_URL --env DELPHIX_SIGNATURE_TOKEN --env DELPHIX_PLATFORMS --env DELPHIX_APPLIANCE_VERSION --volume /media/praveen/new/delphix/appliance-build:/opt/appliance-build --workdir /opt/appliance-build appliance-build gradle buildInternalMinimalKvm
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :live-build:ancillaryRepository
+ set -o errexit
+ set -o pipefail
+ OUTPUT_DIR=/opt/appliance-build/live-build/build/ancillary-repository
++ resolve_s3_uri '' '' dlpx-app-gate/master/build-package/post-push/latest
++ local pkg_uri=
++ local pkg_prefix=
++ local latest_subprefix=dlpx-app-gate/master/build-package/post-push/latest
++ local bucket=snapshot-de-images
++ local jenkinsid=jenkins-ops
++ local resolved_uri
++ [[ -n '' ]]
++ [[ '' == s3* ]]
++ [[ -n '' ]]
++ [[ -n dlpx-app-gate/master/build-package/post-push/latest ]]
++ aws s3 cp --quiet s3://snapshot-de-images/builds/jenkins-ops/dlpx-app-gate/master/build-package/post-push/latest .
+++ cat latest
cat: latest: No such file or directory
++ resolved_uri=s3://snapshot-de-images/
++ rm -f latest
++ aws s3 ls s3://snapshot-de-images/
++ echo ''\''s3://snapshot-de-images/'\'' not found.'
's3://snapshot-de-images/' not found.
++ exit 1
+ AWS_S3_URI_VIRTUALIZATION=

> Task :live-build:ancillaryRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':live-build:ancillaryRepository'.
> Process 'command '/opt/appliance-build/scripts/build-ancillary-repository.sh'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
1 actionable task: 1 executed

**Comment by prakashsurya** [comment]
Yes, this is expected unless you're running this on a "bootstrap" VM as described in the quickstart, which is only available to Delphix employees (unfortunately). Are you a Delphix employee?

If not, what are you trying to accomplish?

**Comment by pnumboori** [comment]
No not a Dephix employee.
I am trying to follow the instructions provided to build a delphix appliance on my sandbox area.
So the github documentation for creating the appliance build will not work?
Thanks

**Comment by prakashsurya** [comment]
Unfortunately, no. The build relies on artifacts that aren't available outside of Delphix, so it won't work unless you have access to "dlpxdc.co".

The Delphix specific parts could be removed, resulting in a regular Ubuntu system running a ZFS root filesystem, but it won't have any Delphix specific components installed.

**Comment by pnumboori** [comment]
ok.thanks - will close the issues now.

**Comment by pnumboori** [comment]
ok.thanks - will close the issues now.
