### ISSUE TITLE
Docker crash and failure to pull from production.cloudflare.docker.com

### ISSUE THREAD

**Issue by shartse** [delphix/appliance-build#269]
Two appliance builds had various sub-jobs hit the docker crash symptoms similar to those outlined in https://github.com/delphix/appliance-build/issues/240 with the final error:
```
error pulling image configuration: 
Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/45/452a96d81c30a1e426bc250428263ac9ca3f47c9bf086f876d11cb39cf57aeec/data?verify=1555133298-2Ixx%2FCqqkbb5ljsiE3nTykoa22M%3D: 
dial tcp: lookup production.cloudflare.docker.com: No address associated with hostname"
```
Both builds were started around the same time, perhaps there was some kind of cloudfare outage in this time frame?

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/841/console
internal-qa-aws, internal-dev-esx

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/840/console
internal-qa-aws, internal-dev-esx, internal-qa-gcp, internal-dev-aws, internal-dev-azure,internal-qa-azure, internal-qa-esx, internal-dev-gcp

**Comment by pzakha** [comment]
Closing this as we removed docker from the build.
