### ISSUE TITLE
AWS VM fails to start up due to dns issue

### ISSUE THREAD

**Issue by pcd1193182** [delphix/appliance-build#314]
See http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/9592/console and http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/80/ for examples.  This appears to be an environmental failure to me, but is there any way we can make it less common? It happened twice in one week.

**Comment by prakashsurya** [comment]
I think, this would be better served as a TOOL bug in JIRA, since that code is executed by the Jenkins job in the devop-gate.

**Comment by pzakha** [comment]
Closing this as we haven't seen this in a while and the links have expired.
