### ISSUE TITLE
pip install fails due to missing module on artifactory

### ISSUE THREAD

**Issue by jwk404** [delphix/appliance-build#318]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/1273/console

```
13:03:22  Collecting colorama<=0.3.9,>=0.2.5 (from awscli)
13:03:22    Downloading http://artifactory.delphix.com/artifactory/api/pypi/delphix-virtual-pypi/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
13:03:22  Collecting botocore==1.12.174 (from awscli)
13:03:22    Could not find a version that satisfies the requirement botocore==1.12.174 (from awscli) (from versions: 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.10.0,
...
13:03:22  No matching distribution found for botocore==1.12.174 (from awscli)
```

Looking at artifactory, botocore 1.12.174 is indeed there, and I was able to download it. However the modification time listed was just minutes prior to the failure. I'm not sure whether one or both systems uses NTP, or whether the artifactory modification time is the same as availability to consumers, or whether something else is going on here.

**Comment by shartse** [comment]
Hit something similar again:
```
2:29:01  Collecting botocore==1.15.23 (from awscli)
12:29:02    Could not find a version that satisfies the requirement botocore==1.15.23 (
```
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/2765/console

Subsequent builds went fine.

**Comment by don-brady** [comment]
Another one:
```
13:28:30  Collecting colorama<0.4.4,>=0.2.5; python_version != "3.4" (from awscli)
13:28:30    Downloading http://artifactory.delphix.com/artifactory/api/pypi/delphix-virtual-pypi/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
13:28:30  Collecting botocore==1.15.42 (from awscli)
13:28:30    Could not find a version that satisfies the requirement botocore==1.15.42 (from awscli)
13:28:31  No matching distribution found for botocore==1.15.42 (from awscli)
```

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/6.0/job/stage/job/post-push/492/console

**Comment by pzakha** [comment]
Closing this as we have a JIRA bug filed for this already: https://jira.delphix.com/browse/TOOL-8365
