### ISSUE TITLE
appliance-build failed with 'aws s3 cp' dumping core

### ISSUE THREAD

**Issue by manoj-joseph** [delphix/appliance-build#424]
appliance-build failed with 'aws s3 cp' dumping core.

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/6.0/job/patch/job/nightly/140/

> [2020-02-10T08:13:33.626Z] + aws s3 cp --only-show-errors s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/6.0/patch/nightly/140/internal-minimal-hyperv/internal-minimal-hyperv.debs.tar.gz .
> [2020-02-10T08:13:34.322Z] /var/tmp/jenkins/workspace/devops-gate/master/appliance-build/6.0/patch/nightly/appliance-build/scripts/fetch-livebuild-artifacts.sh: line 32: 15538 Segmentation fault      (core dumped) aws s3 cp --only-show-errors "$S3_URI/$debs_file" .
> [2020-02-10T08:13:50.083Z] 
> [2020-02-10T08:13:50.083Z] > Task :live-build:fetchLiveBuildArtifacts FAILED

**Comment by manojdelphix** [comment]
This looks like a one-off failure. The next two runs passed.

**Comment by manojdelphix** [comment]
Turns out it was not a one off.

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/nightly/390/execution/node/525/log/

**Comment by sdimitro** [comment]
Hit this again:

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/6.0/job/patch/job/post-push/6548/console

**Comment by prakashsurya** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage0/job/post-push/1157/console

**Comment by don-brady** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage0/job/post-push/4752/execution/node/381/log/

**Comment by don-brady** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/5378/

**Comment by jwk404** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage0/job/post-push/7396/consoleFull

**Comment by sdimitro** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage0/job/post-push/7723/execution/node/404/log/

**Comment by jwk404** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage0/job/post-push/8605/console

**Comment by sdimitro** [comment]
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage0/job/post-push/9152/execution/node/294/log/

**Comment by don-brady** [comment]
http://ops.jenkins.delphix.com/job/appliance-build-stage0/job/post-push/55/execution/node/288/log/

**Comment by pcd1193182** [comment]
http://ops.jenkins.delphix.com/job/appliance-build/job/master/job/post-push/78/

**Comment by manoj-joseph** [comment]
http://ops.jenkins.delphix.com/job/appliance-build-stage0/job/post-push/3713/console

**Comment by manoj-joseph** [comment]
http://ops.jenkins.delphix.com/job/appliance-build-stage0/job/post-push/4698/consoleFull

**Comment by grwilson** [comment]
Jira tracking bug: https://delphix.atlassian.net/browse/TOOL-16683
