### ISSUE TITLE
aws s3 sync hangs

### ISSUE THREAD

**Issue by manojdelphix** [delphix/appliance-build#430]
aws s3 sync took over 3 hours, likely hung, and was timed out. 

> 13:34:36  + aws s3 sync --delete --only-show-errors . s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/2546/internal-dev-azure/
> 16:30:24  Calling Pipeline was cancelled
> 16:30:24  Sending interrupt signal to process
> 16:30:25  Calling Pipeline was cancelled
> 16:30:28  Sending interrupt signal to process
> 16:30:33  /var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/master/post-push/appliance-build/live-build/build/artifacts@tmp/durable-52dfcd68/script.sh: line 1: 22208 Terminated              aws s3 sync --delete --only-show-errors . s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/2546/internal-dev-azure/
> 16:30:33  script returned exit code 143
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/31705/

**Comment by pzakha** [comment]
Thanks for filing a bug. This looks like https://github.com/delphix/appliance-build/issues/183. I've added a comment there and closing this as a duplicate.
