### ISSUE TITLE
Stop using merge commits

### ISSUE THREAD

**Issue by prakashsurya** [delphix/appliance-build#9]
Currently the commit history looks something like this:
```
$ g lg
*   1e94e60 (HEAD -> master, origin/staging, origin/master) Merge #6
|\
| * 7926715 Add fio to the image
|/
*   561d294 Merge #4
|\
| * 458ce05 Enforce "shellcheck" and "shfmtcheck" via CI tests
|/
*   c9336a0 Merge #3
|\
| * dbbc034 Explicitly install "generic" kernel and tools
|/
*   4c62c90 Merge #1
|\
| * 769dccc Clone full history of dlpx-app-gate repository
|/
* 164a3ca Delphix Appliance Build - Initial Commit
```
This is because "bors" doesn't yet support anything but using merge commits to land changes to the master branch.

There's an upstream bug about "bors" supporting a mechanism that would eliminate these merge commits, and result in a "flat" commit history; see: https://github.com/bors-ng/bors-ng/issues/138

This issue is to serve as a reminder to adopt a flat commit history if/when "bors" starts to support a non-merge based workflow; as well as to document why we're currently using merge commits (i.e. because that's all that "bors" currently supports).

**Comment by pzakha** [comment]
"Fixed" as we are not using bors anymore.
