### ISSUE TITLE
Run apt-get update before running ansible-playbook step

### ISSUE THREAD

**Issue by pzakha** [delphix/appliance-build#97]
We currently have a bunch of
```
- apt:
	update_cache: yes
```
statements in appliance-build's ansible roles before we install any apt packages.

Doing it this way is time consuming and fragile (if we forget to run apt-update we may have unexpected results). Instead, we should run it in the 80-ansible-playbook.binary hook, right before we execute ansible playbook.

**Comment by prakashsurya** [comment]
We should also clear the apt cache(s) afterwards, to reduce the image size and force users to update the cache after using the image to provision a VM. Similar to what’s common in Dockerfiles.
